/* The following code was generated by JFlex 1.6.1 */

package Scanner;

import Clases.Tipo_token;
import static Clases.Tipo_token.*;
import Clases.ScannerException;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Meli/Documents/TEC/2018 2do Sem/Compiladores e Interpretes/Proyecto/CompiladorABC/CompiladorABC/src/Scanner/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\4\1\6\1\6\1\4\22\0\1\63\1\61\1\60"+
    "\1\57\3\61\1\0\1\7\1\11\1\10\1\46\1\45\1\50\1\55"+
    "\1\5\1\62\11\2\1\54\1\45\1\52\1\47\1\51\1\0\1\61"+
    "\1\14\1\17\1\30\1\34\1\20\1\36\1\21\1\33\1\23\1\1"+
    "\1\42\1\26\1\43\1\24\1\25\1\40\1\1\1\15\1\32\1\27"+
    "\1\37\1\44\1\35\1\56\1\16\1\1\1\53\1\0\1\53\3\61"+
    "\1\14\1\17\1\30\1\34\1\20\1\36\1\21\1\33\1\23\1\1"+
    "\1\42\1\26\1\43\1\24\1\25\1\40\1\1\1\15\1\32\1\27"+
    "\1\37\1\44\1\35\1\56\1\16\1\1\1\12\1\61\1\13\1\61"+
    "\6\0\1\6\252\0\2\22\115\0\1\31\u1ea8\0\1\6\1\6\u0100\0"+
    "\1\41\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\4\5\1\1\5\2"+
    "\1\1\6\2\1\1\10\2\5\5\1\2\2\1\1\3"+
    "\1\6\1\7\1\3\1\10\3\0\1\4\11\2\4\11"+
    "\1\0\2\2\1\5\6\2\3\0\3\2\1\0\1\2"+
    "\1\11\1\2\1\0\3\2\1\0\7\2\1\12\1\2"+
    "\1\13\3\0\1\14\1\0\1\6\2\7\1\10\1\15"+
    "\2\0\1\4\7\2\1\0\1\2\1\0\5\2\2\0"+
    "\3\2\2\0\1\2\1\11\4\2\1\13\1\14\1\15"+
    "\1\0\1\15\1\7\1\0\1\4\3\2\1\0\1\2"+
    "\1\0\2\2\2\0\4\2\1\0\3\2\1\15\1\0"+
    "\1\16\1\2\1\0\1\2\2\0\2\2\1\0\2\2"+
    "\1\0\4\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\64\0\320\0\u0104\0\u0138"+
    "\0\64\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4"+
    "\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784"+
    "\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924"+
    "\0\u0958\0\u098c\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4"+
    "\0\u0af8\0\u0b2c\0\64\0\u0b60\0\150\0\u0b94\0\u0bc8\0\u0bfc"+
    "\0\150\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0d34\0\u0d68"+
    "\0\u0d9c\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\u0f08"+
    "\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\u100c\0\u1040\0\u1074\0\u10a8"+
    "\0\u10dc\0\u1110\0\u1144\0\u1178\0\u11ac\0\u06b4\0\u11e0\0\u071c"+
    "\0\u1214\0\u1248\0\u127c\0\u1214\0\u12b0\0\u12e4\0\u1318\0\u134c"+
    "\0\u1380\0\u13b4\0\u13e8\0\u141c\0\u08f0\0\u1450\0\u1484\0\u14b8"+
    "\0\u14ec\0\u1520\0\u1554\0\u1588\0\u15bc\0\u15f0\0\u1624\0\u1658"+
    "\0\u168c\0\u16c0\0\u16f4\0\u1728\0\u175c\0\u1790\0\u17c4\0\u17f8"+
    "\0\u182c\0\u1860\0\u1894\0\u18c8\0\u18fc\0\u1930\0\u1964\0\u1998"+
    "\0\u19cc\0\64\0\64\0\u1a00\0\u1a34\0\u1380\0\u1a68\0\u1a9c"+
    "\0\u13e8\0\u1ad0\0\u1b04\0\u1b38\0\u1b6c\0\u1ba0\0\u1bd4\0\u1c08"+
    "\0\u1c3c\0\u1c70\0\u1ca4\0\u1cd8\0\u1d0c\0\u1d40\0\u1d74\0\u1da8"+
    "\0\u1ddc\0\u1e10\0\u1e44\0\u1a34\0\u1e78\0\64\0\u1eac\0\u1ee0"+
    "\0\u1f14\0\u1f48\0\u1f7c\0\u1fb0\0\u1fe4\0\u2018\0\u204c\0\u2080"+
    "\0\u20b4\0\u20e8\0\u211c\0\u2150\0\u2184";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\1\6\1\0\1\7\1\10"+
    "\1\11\1\12\1\2\1\13\1\14\1\3\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\3\1\31\1\32\1\33\1\34\1\35"+
    "\1\2\1\3\1\36\1\37\1\11\1\40\1\11\1\41"+
    "\1\42\1\43\1\11\1\10\1\44\1\45\1\46\1\47"+
    "\1\2\1\50\1\5\65\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\6\3\1\0\6\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\1\52\1\53\11\0\6\52\1\0\6\52"+
    "\1\0\7\52\1\0\3\52\10\0\1\54\1\52\3\0"+
    "\1\53\6\0\1\55\41\0\1\11\24\0\1\56\122\0"+
    "\1\11\14\0\13\57\1\60\50\57\1\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\1\3\1\61\4\3\1\0"+
    "\1\3\1\62\4\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\4\3\1\63"+
    "\1\3\1\0\6\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\2\3\1\64"+
    "\1\3\1\65\1\3\1\0\2\3\1\66\3\3\1\0"+
    "\7\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\2\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\6\3\1\0\1\3\1\67\1\3\1\70"+
    "\2\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\2\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\6\3\1\0\2\3\1\71"+
    "\3\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\25\0\1\72\11\0"+
    "\1\73\26\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\6\3\1\0\1\3\1\74\4\3\1\0\4\3\1\75"+
    "\2\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\2\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\6\3\1\76\1\77\1\3\1\100\3\3"+
    "\1\0\7\3\1\0\3\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\2\0\2\3\2\0\1\51"+
    "\2\0\1\51\3\0\1\3\1\101\4\3\1\0\6\3"+
    "\1\0\4\3\1\75\2\3\1\0\3\3\6\51\2\0"+
    "\1\51\1\3\1\51\1\0\1\51\1\3\2\0\2\3"+
    "\2\0\1\51\2\0\1\51\3\0\1\102\5\3\1\0"+
    "\2\3\1\103\3\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\1\3\1\104"+
    "\1\105\3\3\1\0\2\3\1\75\3\3\1\0\1\3"+
    "\1\106\5\3\1\0\3\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\2\0\2\3\2\0\1\51"+
    "\2\0\1\51\3\0\1\70\5\3\1\0\2\3\1\107"+
    "\3\3\1\0\1\3\1\37\5\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\21\0"+
    "\1\110\6\0\1\111\3\0\1\112\31\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\4\3\1\113\1\3\1\0"+
    "\4\3\1\114\1\3\1\0\1\3\1\115\5\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\6\3\1\116\1\117\1\3\1\120\3\3\1\0\7\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\2\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\1\3\1\121\4\3\1\122\1\123\5\3\1\0"+
    "\1\3\1\124\5\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\2\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\1\125\5\3\1\126\1\127"+
    "\1\3\1\130\3\3\1\0\5\3\1\131\1\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\6\3\1\0\1\3\1\132\4\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\1\133\1\134\4\3\1\0\6\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\6\3\1\0\2\3\1\62\3\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\1\135\5\3\1\0\6\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\47\0\2\11\63\0\2\11\62\0\1\11\1\0\1\10"+
    "\61\0\1\11\1\0\1\11\1\10\13\0\1\136\57\0"+
    "\1\136\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\6\3\1\0\2\3\1\137\3\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\3\0\1\140\57\0\1\140\1\0\1\141\3\142"+
    "\1\143\1\142\1\0\1\141\1\142\3\141\6\142\1\141"+
    "\6\142\1\141\7\142\1\141\11\142\2\141\3\142\1\144"+
    "\3\142\1\0\1\52\1\145\11\0\6\52\1\0\6\52"+
    "\1\0\7\52\1\0\3\52\10\0\1\54\1\52\3\0"+
    "\1\145\2\0\2\146\2\0\1\51\2\0\1\51\3\0"+
    "\6\146\1\0\6\146\1\0\7\146\1\0\3\146\6\51"+
    "\2\0\1\51\1\146\1\51\1\0\1\51\1\146\2\0"+
    "\2\52\11\0\6\52\1\0\6\52\1\0\7\52\1\0"+
    "\3\52\10\0\1\147\1\52\3\0\1\52\2\0\1\52"+
    "\1\53\11\0\4\52\1\150\1\52\1\0\6\52\1\0"+
    "\7\52\1\0\3\52\10\0\1\151\1\52\3\0\1\53"+
    "\2\0\1\147\1\152\11\0\6\147\1\0\6\147\1\0"+
    "\7\147\1\0\3\147\11\0\1\147\3\0\1\152\1\0"+
    "\4\55\1\5\1\55\1\0\55\55\10\153\1\154\53\153"+
    "\13\57\1\155\134\57\1\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\1\3\1\156\4\3\1\0\6\3\1\0"+
    "\7\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\2\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\6\3\1\0\6\3\1\0\2\3\1\101"+
    "\4\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\2\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\1\157\5\3\1\0\5\3\1\160\1\0"+
    "\6\3\1\161\1\0\3\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\2\0\2\3\2\0\1\51"+
    "\2\0\1\51\3\0\6\3\1\0\4\3\1\162\1\3"+
    "\1\0\7\3\1\0\3\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\2\0\2\3\2\0\1\51"+
    "\2\0\1\51\3\0\5\3\1\163\1\0\6\3\1\0"+
    "\7\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\2\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\6\3\1\0\2\3\1\164\3\3\1\0"+
    "\7\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\2\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\6\3\1\0\6\3\1\0\2\3\1\75"+
    "\4\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\2\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\6\3\1\0\6\3\1\165\1\162\6\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\2\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\6\3\1\0\4\3\1\166\1\3\1\0\7\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\27\0\1\167\1\73\35\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\6\3\1\0\3\3\1\170"+
    "\1\75\1\3\1\0\7\3\1\0\3\3\6\51\2\0"+
    "\1\51\1\3\1\51\1\0\1\51\1\3\27\0\1\73"+
    "\36\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\3\3\1\75\2\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\4\3\1\101\1\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\3\3"+
    "\1\171\2\3\1\0\6\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\1\3\1\172\4\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\6\3\1\0\5\3\1\162\1\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\6\3\1\0\6\3\1\162\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\4\3\1\173"+
    "\1\3\1\0\6\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\6\3\1\0"+
    "\1\3\1\174\4\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\30\0"+
    "\1\73\51\0\1\175\73\0\1\176\37\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\6\3\1\0\4\3\1\75"+
    "\1\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\2\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\1\3\1\177\4\3\1\0"+
    "\6\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\2\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\6\3\1\0\2\3\1\200"+
    "\3\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\45\0\1\11\20\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\6\3\1\0"+
    "\6\3\1\0\7\3\1\0\2\3\1\101\6\51\2\0"+
    "\1\51\1\3\1\51\1\0\1\51\1\3\2\0\2\3"+
    "\2\0\1\51\2\0\1\51\3\0\6\3\1\0\6\3"+
    "\1\0\3\3\1\201\3\3\1\0\3\3\6\51\2\0"+
    "\1\51\1\3\1\51\1\0\1\51\1\3\2\0\2\3"+
    "\2\0\1\51\2\0\1\51\3\0\6\3\1\202\1\64"+
    "\5\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\30\0\1\203\35\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\6\3\1\0"+
    "\4\3\1\204\1\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\6\3\1\126"+
    "\1\127\5\3\1\0\7\3\1\0\3\3\6\51\2\0"+
    "\1\51\1\3\1\51\1\0\1\51\1\3\2\0\2\3"+
    "\2\0\1\51\2\0\1\51\3\0\6\3\1\0\3\3"+
    "\1\70\2\3\1\0\7\3\1\0\3\3\6\51\2\0"+
    "\1\51\1\3\1\51\1\0\1\51\1\3\27\0\1\165"+
    "\36\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\3\3\1\162\2\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\1\3"+
    "\1\205\4\3\1\0\6\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\1\3\1\206\4\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\4\3\1\207\1\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\5\3\1\210\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\6\3\1\0"+
    "\2\3\1\211\3\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\1\3\1\75"+
    "\4\3\1\0\6\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\1\3\1\101"+
    "\4\3\1\0\6\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\61\0"+
    "\1\212\4\0\5\143\2\0\1\143\3\0\6\143\1\0"+
    "\6\143\1\0\7\143\1\0\11\143\2\0\3\143\1\212"+
    "\3\143\1\0\5\143\2\0\1\143\3\0\6\143\1\0"+
    "\6\143\1\0\7\143\1\0\11\143\2\0\3\143\1\213"+
    "\3\143\1\0\1\52\1\145\11\0\4\52\1\150\1\52"+
    "\1\0\6\52\1\0\7\52\1\0\3\52\10\0\1\151"+
    "\1\52\3\0\1\145\2\0\2\146\11\0\6\146\1\0"+
    "\6\146\1\0\7\146\1\0\3\146\11\0\1\146\3\0"+
    "\1\146\2\0\2\147\11\0\6\147\1\0\6\147\1\0"+
    "\7\147\1\0\3\147\11\0\1\147\3\0\1\147\2\0"+
    "\1\52\1\214\11\0\6\52\1\0\6\52\1\0\7\52"+
    "\1\0\3\52\1\0\1\215\1\0\1\215\4\0\1\147"+
    "\1\52\3\0\1\214\2\0\1\147\1\216\11\0\6\147"+
    "\1\0\6\147\1\0\7\147\1\0\3\147\11\0\1\147"+
    "\3\0\1\216\2\0\1\147\1\152\11\0\4\147\1\217"+
    "\1\147\1\0\6\147\1\0\7\147\1\0\3\147\11\0"+
    "\1\147\3\0\1\152\1\0\10\153\1\220\64\153\1\221"+
    "\52\153\1\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\1\222\5\3\1\0\6\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\3\3\1\75\2\3\1\0\2\3\1\75\4\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\2\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\6\3\1\0\2\3\1\223\3\3\1\0\7\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\2\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\4\3\1\224\1\3\1\0\6\3\1\0\7\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\2\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\4\3\1\75\1\3\1\0\6\3\1\0\7\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\2\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\6\3\1\225\1\173\5\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\6\3\1\0\3\3\1\226\2\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\21\0\1\73\44\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\6\3\1\0\2\3\1\75\3\3\1\0"+
    "\7\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\23\0\2\227\41\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\6\3\1\227\1\230\5\3"+
    "\1\0\7\3\1\0\3\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\2\0\2\3\2\0\1\51"+
    "\2\0\1\51\3\0\4\3\1\77\1\3\1\0\6\3"+
    "\1\0\7\3\1\0\3\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\2\0\2\3\2\0\1\51"+
    "\2\0\1\51\3\0\5\3\1\231\1\0\6\3\1\0"+
    "\7\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\2\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\6\3\1\0\1\3\1\75\4\3\1\0"+
    "\7\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\2\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\6\3\1\0\6\3\1\110\1\113\6\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\23\0\2\232\55\0\1\233\47\0\2\3"+
    "\2\0\1\51\2\0\1\51\3\0\6\3\1\232\1\234"+
    "\5\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\2\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\1\3\1\235\4\3\1\0"+
    "\6\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\2\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\6\3\1\0\1\3\1\71"+
    "\4\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\30\0\1\165\67\0"+
    "\1\73\31\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\6\3\1\0\6\3\1\0\1\3\1\75\5\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\6\3\1\0\6\3\1\0\3\3\1\236\3\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\6\3\1\0\5\3\1\237\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\76\1\77\5\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\6\3\1\0"+
    "\6\3\1\0\7\3\1\240\1\241\2\3\6\51\2\0"+
    "\1\51\1\3\1\51\1\0\1\51\1\3\2\0\2\3"+
    "\2\0\1\51\2\0\1\51\3\0\5\3\1\242\1\0"+
    "\5\3\1\243\1\0\7\3\1\0\3\3\6\51\2\0"+
    "\1\51\1\3\1\51\1\0\1\51\1\3\2\0\1\52"+
    "\1\214\11\0\6\52\1\0\6\52\1\0\7\52\1\0"+
    "\3\52\10\0\1\147\1\52\3\0\1\214\3\0\1\244"+
    "\57\0\1\244\2\0\1\147\1\216\11\0\6\147\1\0"+
    "\6\147\1\0\7\147\1\0\3\147\1\0\1\245\1\0"+
    "\1\245\5\0\1\147\3\0\1\216\1\246\10\153\1\220"+
    "\1\221\52\153\1\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\2\3\1\75\3\3\1\0\6\3\1\0\7\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\2\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\1\3\1\67\4\3\1\0\6\3\1\0\7\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\2\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\1\113\5\3\1\0\6\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\25\0\1\73\40\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\4\3\1\247\1\3\1\0\6\3\1\0"+
    "\7\3\1\0\3\3\6\51\2\0\1\51\1\3\1\51"+
    "\1\0\1\51\1\3\25\0\1\165\40\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\6\3\1\0\1\3\1\162"+
    "\4\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\2\0\2\3\2\0"+
    "\1\51\2\0\1\51\3\0\6\3\1\250\1\251\5\3"+
    "\1\0\7\3\1\0\3\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\25\0\1\252\66\0\1\253"+
    "\35\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\1\3\1\254\4\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\6\3"+
    "\1\0\4\3\1\231\1\3\1\0\7\3\1\0\3\3"+
    "\6\51\2\0\1\51\1\3\1\51\1\0\1\51\1\3"+
    "\2\0\2\3\2\0\1\51\2\0\1\51\3\0\1\223"+
    "\5\3\1\0\6\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\2\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\6\3\1\0"+
    "\4\3\1\255\1\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\21\0"+
    "\1\256\44\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\4\3\1\67\1\3\1\0\6\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\1\3\1\257\4\3\1\0\6\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\2\0\2\3\2\0\1\51\2\0\1\51\3\0"+
    "\4\3\1\260\1\3\1\0\6\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\3\0\1\244\57\0\1\244\1\246\1\0\2\3"+
    "\2\0\1\51\2\0\1\51\3\0\1\173\5\3\1\0"+
    "\6\3\1\0\7\3\1\0\3\3\6\51\2\0\1\51"+
    "\1\3\1\51\1\0\1\51\1\3\25\0\1\110\40\0"+
    "\2\3\2\0\1\51\2\0\1\51\3\0\6\3\1\0"+
    "\1\3\1\113\4\3\1\0\7\3\1\0\3\3\6\51"+
    "\2\0\1\51\1\3\1\51\1\0\1\51\1\3\22\0"+
    "\1\73\64\0\2\250\41\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\5\3\1\75\1\0\6\3\1\0\7\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\2\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\6\3\1\261\1\262\5\3\1\0\7\3\1\0"+
    "\3\3\6\51\2\0\1\51\1\3\1\51\1\0\1\51"+
    "\1\3\35\0\1\73\30\0\2\3\2\0\1\51\2\0"+
    "\1\51\3\0\1\263\5\3\1\0\6\3\1\0\7\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\2\0\2\3\2\0\1\51\2\0\1\51"+
    "\3\0\6\3\1\0\6\3\1\0\2\3\1\264\4\3"+
    "\1\0\3\3\6\51\2\0\1\51\1\3\1\51\1\0"+
    "\1\51\1\3\26\0\1\225\37\0\2\3\2\0\1\51"+
    "\2\0\1\51\3\0\6\3\1\0\2\3\1\173\3\3"+
    "\1\0\7\3\1\0\3\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\2\0\2\3\2\0\1\51"+
    "\2\0\1\51\3\0\6\3\1\0\6\3\1\0\7\3"+
    "\1\0\1\3\1\75\1\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\2\0\2\3\2\0\1\51"+
    "\2\0\1\51\3\0\6\3\1\0\6\3\1\0\5\3"+
    "\1\265\1\3\1\0\3\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\2\0\2\3\2\0\1\51"+
    "\2\0\1\51\3\0\1\3\1\162\4\3\1\0\6\3"+
    "\1\0\7\3\1\0\3\3\6\51\2\0\1\51\1\3"+
    "\1\51\1\0\1\51\1\3\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8632];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\3\1\1\11\43\1\3\0"+
    "\13\1\1\11\2\1\1\0\11\1\3\0\3\1\1\0"+
    "\3\1\1\0\3\1\1\0\12\1\3\0\1\1\1\0"+
    "\5\1\2\0\10\1\1\0\1\1\1\0\5\1\2\0"+
    "\3\1\2\0\6\1\2\11\1\1\1\0\2\1\1\0"+
    "\4\1\1\0\1\1\1\0\2\1\2\0\4\1\1\0"+
    "\4\1\1\0\1\11\1\1\1\0\1\1\2\0\2\1"+
    "\1\0\2\1\1\0\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public String lexeme;

    public int yyline() {
    	return this.yyline;
    }

    public void error(String msg, String caracteres, int linea) throws ScannerException {
        throw new ScannerException(msg, caracteres, linea+1);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 236) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tipo_token yylex() throws java.io.IOException, ScannerException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { error("El caracter es inválido", yytext(), yyline()); return ERROR;
            }
          case 15: break;
          case 2: 
            { return IDENTIFICADOR;
            }
          case 16: break;
          case 3: 
            { return INTEGER;
            }
          case 17: break;
          case 4: 
            { /*Ignore*/
            }
          case 18: break;
          case 5: 
            { return OPERADOR;
            }
          case 19: break;
          case 6: 
            { error("Identificador erróneo: no se puede utilizar caracteres especiales en los identificadores.", yytext(),yyline()); return ERROR;
            }
          case 20: break;
          case 7: 
            { error("Número erróneo: no se puede ingresar letras dentro de un número.", yytext(),yyline()); return ERROR;
            }
          case 21: break;
          case 8: 
            { error("Número erróneo: no se puede finalizar un número con punto", yytext(),yyline()); return ERROR;
            }
          case 22: break;
          case 9: 
            { return PALABRA_RESERVADA;
            }
          case 23: break;
          case 10: 
            { error("Número erróneo: no se puede iniciar un número con punto", yytext(),yyline()); return ERROR;
            }
          case 24: break;
          case 11: 
            { return CHAR;
            }
          case 25: break;
          case 12: 
            { return STRING;
            }
          case 26: break;
          case 13: 
            { return FLOAT;
            }
          case 27: break;
          case 14: 
            { return ERROR;
            }
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
