/* The following code was generated by JFlex 1.7.0 */

package Scanner;
import Parser.sym;
import java_cup.runtime.*;
import Clases.ScannerException;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>C:/Users/Meli/Documents/TEC/2018 2do Sem/Compiladores e Interpretes/Proyecto/CompiladorABC/CompiladorABC/src/Scanner/Lexer.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMENTARIOS1 = 2;
  public static final int COMENTARIOS2 = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\4\1\10\1\10\1\4\22\0\1\52\1\6\1\50"+
    "\4\6\1\0\1\11\1\46\1\12\1\44\1\37\1\45\1\5\1\7"+
    "\1\51\11\2\1\47\1\40\1\43\1\42\1\41\1\0\1\6\1\24"+
    "\1\14\1\25\1\33\1\15\1\34\1\16\1\26\1\20\2\1\1\23"+
    "\1\1\1\21\1\22\2\1\1\27\1\31\1\32\1\35\1\36\4\1"+
    "\1\6\1\0\4\6\1\24\1\14\1\25\1\33\1\15\1\34\1\16"+
    "\1\26\1\20\2\1\1\23\1\1\1\21\1\22\2\1\1\27\1\31"+
    "\1\32\1\35\1\36\4\1\1\13\1\6\1\53\1\6\6\0\1\10"+
    "\153\0\1\6\76\0\2\17\115\0\1\30\u1ea8\0\1\10\1\10\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\2\2\1\1\4\2\1\1\4\2\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\1\1\3\3\4\1\22\1\23\1\24\1\3\1\25"+
    "\1\26\1\4\1\27\3\2\1\0\5\2\2\0\2\2"+
    "\1\0\3\2\1\30\1\31\1\32\2\0\1\33\1\0"+
    "\1\23\1\24\1\25\1\24\1\34\1\35\2\2\1\36"+
    "\2\37\4\2\2\0\2\2\2\40\1\2\1\41\2\0"+
    "\2\34\1\0\1\24\1\0\3\2\1\0\1\2\1\42"+
    "\1\43\2\0\3\2\1\0\2\34\1\0\1\24\2\44"+
    "\1\2\1\0\1\2\2\45\2\0\3\2\1\46\1\0"+
    "\1\2\1\0\1\2\1\0\1\47\1\2\1\47\1\0"+
    "\1\2\1\50\2\51\1\0\1\2\1\0\1\2\2\52"+
    "\2\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\204\0\u0108"+
    "\0\u0134\0\u0160\0\204\0\204\0\u018c\0\u01b8\0\u01e4\0\u0210"+
    "\0\u023c\0\u0268\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370"+
    "\0\204\0\204\0\u039c\0\204\0\u03c8\0\204\0\u03f4\0\204"+
    "\0\204\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04d0\0\204\0\u04fc"+
    "\0\u0528\0\u0554\0\u0580\0\u0108\0\u05ac\0\204\0\u05d8\0\u0604"+
    "\0\u0630\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738\0\u0764"+
    "\0\u0790\0\u07bc\0\u07e8\0\u0814\0\u0840\0\u086c\0\u0898\0\204"+
    "\0\204\0\204\0\u08c4\0\u0420\0\204\0\u08f0\0\u091c\0\u0948"+
    "\0\u0974\0\u09a0\0\u09cc\0\u09f8\0\u0a24\0\u0a50\0\260\0\204"+
    "\0\260\0\u0a7c\0\u0aa8\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58\0\u0b84"+
    "\0\u0bb0\0\204\0\260\0\u0bdc\0\260\0\u0c08\0\u0c34\0\u0974"+
    "\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4\0\u0d10\0\u0d3c\0\u0d68\0\u0d94"+
    "\0\u0dc0\0\260\0\260\0\u0dec\0\u0e18\0\u0e44\0\u0e70\0\u0e9c"+
    "\0\u0ec8\0\u0c8c\0\u0ef4\0\u0f20\0\204\0\204\0\260\0\u0f4c"+
    "\0\u0f78\0\u0fa4\0\204\0\260\0\u0fd0\0\u0ffc\0\u1028\0\u1054"+
    "\0\u1080\0\u10ac\0\u10ac\0\u10d8\0\u1104\0\u1130\0\u115c\0\204"+
    "\0\u1188\0\260\0\u11b4\0\u11e0\0\260\0\204\0\260\0\u120c"+
    "\0\u1238\0\u1264\0\u1290\0\204\0\260\0\204\0\260";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\2\7\1\10\1\4\1\11\1\0"+
    "\1\12\1\13\1\14\1\15\1\16\1\5\1\17\1\20"+
    "\2\5\1\21\1\5\1\22\1\5\1\23\1\24\1\25"+
    "\1\5\1\26\1\27\1\5\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\7\1\4\12\44\1\45\41\44\53\46\1\47\55\0"+
    "\2\5\3\0\1\50\2\0\1\50\2\0\3\5\1\0"+
    "\10\5\1\0\6\5\7\0\1\50\2\0\1\5\3\0"+
    "\1\51\1\52\2\0\1\53\6\0\3\51\1\0\10\51"+
    "\1\0\6\51\12\0\1\52\4\0\1\54\46\0\1\54"+
    "\11\0\1\55\56\0\1\56\42\0\2\5\3\0\1\50"+
    "\2\0\1\50\2\0\1\5\1\57\1\5\1\0\2\5"+
    "\1\60\5\5\1\0\6\5\7\0\1\50\2\0\1\5"+
    "\3\0\2\5\3\0\1\50\2\0\1\50\2\0\3\5"+
    "\1\0\1\5\1\61\6\5\1\0\6\5\7\0\1\50"+
    "\2\0\1\5\23\0\1\62\33\0\2\5\3\0\1\50"+
    "\2\0\1\50\2\0\3\5\1\0\1\5\1\63\6\5"+
    "\1\0\6\5\7\0\1\50\2\0\1\5\3\0\2\5"+
    "\3\0\1\50\2\0\1\50\2\0\3\5\1\0\2\5"+
    "\1\64\5\5\1\0\6\5\7\0\1\50\2\0\1\5"+
    "\3\0\2\5\3\0\1\50\2\0\1\50\2\0\3\5"+
    "\1\0\2\5\1\65\3\5\1\66\1\5\1\0\6\5"+
    "\7\0\1\50\2\0\1\5\3\0\2\5\3\0\1\50"+
    "\2\0\1\50\2\0\1\5\1\67\1\5\1\0\10\5"+
    "\1\0\6\5\7\0\1\50\2\0\1\5\30\0\1\70"+
    "\3\0\1\71\22\0\2\5\3\0\1\50\2\0\1\50"+
    "\2\0\3\5\1\0\6\5\1\72\1\5\1\0\1\5"+
    "\1\73\4\5\7\0\1\50\2\0\1\5\3\0\2\5"+
    "\3\0\1\50\2\0\1\50\2\0\3\5\1\74\1\75"+
    "\7\5\1\0\6\5\7\0\1\50\2\0\1\5\3\0"+
    "\2\5\3\0\1\50\2\0\1\50\2\0\3\5\1\0"+
    "\10\5\1\0\4\5\1\76\1\5\7\0\1\50\2\0"+
    "\1\5\3\0\2\5\3\0\1\50\2\0\1\50\2\0"+
    "\3\5\1\0\4\5\1\77\3\5\1\0\6\5\7\0"+
    "\1\50\2\0\1\5\44\0\1\100\52\0\1\101\1\102"+
    "\13\0\1\103\46\0\1\103\3\0\7\104\1\0\2\104"+
    "\1\0\3\104\1\0\10\104\1\0\7\104\1\0\6\104"+
    "\1\0\1\105\2\104\2\0\1\51\1\106\2\0\1\53"+
    "\6\0\3\51\1\0\10\51\1\0\6\51\12\0\1\106"+
    "\2\0\12\44\1\0\41\44\46\0\1\47\5\0\53\46"+
    "\2\0\2\107\3\0\1\50\2\0\1\50\2\0\3\107"+
    "\1\0\10\107\1\0\6\107\7\0\1\50\2\0\1\107"+
    "\3\0\2\51\2\0\1\110\6\0\3\51\1\0\10\51"+
    "\1\0\6\51\12\0\1\51\3\0\1\51\1\52\2\0"+
    "\1\111\6\0\1\51\1\112\1\51\1\0\10\51\1\0"+
    "\6\51\12\0\1\52\3\0\1\110\1\113\2\0\1\114"+
    "\6\0\3\110\1\0\10\110\1\0\6\110\12\0\1\113"+
    "\2\0\4\55\1\0\3\55\1\0\43\55\1\0\2\5"+
    "\3\0\1\50\2\0\1\50\2\0\2\5\1\115\1\0"+
    "\10\5\1\0\6\5\7\0\1\50\2\0\1\5\3\0"+
    "\2\5\3\0\1\50\2\0\1\50\2\0\3\5\1\0"+
    "\2\5\1\116\5\5\1\0\6\5\7\0\1\50\2\0"+
    "\1\5\3\0\2\5\3\0\1\50\2\0\1\50\2\0"+
    "\3\5\1\0\10\5\1\0\2\5\1\117\3\5\7\0"+
    "\1\50\2\0\1\5\34\0\1\120\22\0\2\5\3\0"+
    "\1\50\2\0\1\50\2\0\3\5\1\0\10\5\1\0"+
    "\1\5\1\121\4\5\7\0\1\50\2\0\1\5\3\0"+
    "\2\5\3\0\1\50\2\0\1\50\2\0\3\5\1\0"+
    "\1\5\1\122\6\5\1\0\6\5\7\0\1\50\2\0"+
    "\1\5\3\0\2\5\3\0\1\50\2\0\1\50\2\0"+
    "\3\5\1\0\1\5\1\123\6\5\1\0\6\5\7\0"+
    "\1\50\2\0\1\5\3\0\2\5\3\0\1\50\2\0"+
    "\1\50\2\0\3\5\1\0\4\5\1\124\3\5\1\0"+
    "\6\5\7\0\1\50\2\0\1\5\3\0\2\5\3\0"+
    "\1\50\2\0\1\50\2\0\3\5\1\0\4\5\1\125"+
    "\3\5\1\0\6\5\7\0\1\50\2\0\1\5\24\0"+
    "\1\126\60\0\1\127\25\0\2\5\3\0\1\50\2\0"+
    "\1\50\2\0\3\5\1\0\2\5\1\130\5\5\1\0"+
    "\6\5\7\0\1\50\2\0\1\5\3\0\2\5\3\0"+
    "\1\50\2\0\1\50\2\0\3\5\1\0\7\5\1\131"+
    "\1\0\6\5\7\0\1\50\2\0\1\5\40\0\1\132"+
    "\16\0\2\5\3\0\1\50\2\0\1\50\2\0\3\5"+
    "\1\0\10\5\1\0\5\5\1\133\7\0\1\50\2\0"+
    "\1\5\3\0\2\5\3\0\1\50\2\0\1\50\2\0"+
    "\3\5\1\0\1\5\1\134\6\5\1\0\6\5\7\0"+
    "\1\50\2\0\1\5\3\0\2\5\3\0\1\50\2\0"+
    "\1\50\2\0\3\5\1\0\7\5\1\135\1\0\6\5"+
    "\7\0\1\50\2\0\1\5\4\0\1\136\2\0\1\137"+
    "\43\0\1\136\3\0\1\51\1\106\2\0\1\111\6\0"+
    "\1\51\1\112\1\51\1\0\10\51\1\0\6\51\12\0"+
    "\1\106\3\0\2\107\11\0\3\107\1\0\10\107\1\0"+
    "\6\107\12\0\1\107\3\0\2\110\11\0\3\110\1\0"+
    "\10\110\1\0\6\110\12\0\1\110\3\0\1\110\1\140"+
    "\2\0\1\114\6\0\3\110\1\0\10\110\1\0\6\110"+
    "\12\0\1\140\3\0\1\51\1\141\2\0\1\110\6\0"+
    "\3\51\1\0\10\51\1\0\6\51\5\0\2\142\3\0"+
    "\1\141\3\0\1\110\1\113\2\0\1\114\6\0\1\110"+
    "\1\143\1\110\1\0\10\110\1\0\6\110\12\0\1\113"+
    "\4\0\1\114\2\0\1\114\43\0\1\114\3\0\2\5"+
    "\3\0\1\50\2\0\1\50\2\0\3\5\1\144\1\145"+
    "\7\5\1\0\6\5\7\0\1\50\2\0\1\5\3\0"+
    "\2\5\3\0\1\50\2\0\1\50\2\0\3\5\1\0"+
    "\3\5\1\146\4\5\1\0\6\5\7\0\1\50\2\0"+
    "\1\5\3\0\2\5\3\0\1\50\2\0\1\50\2\0"+
    "\2\5\1\147\1\0\10\5\1\0\6\5\7\0\1\50"+
    "\2\0\1\5\3\0\2\5\3\0\1\50\2\0\1\50"+
    "\2\0\3\5\1\0\10\5\1\150\1\151\5\5\7\0"+
    "\1\50\2\0\1\5\3\0\2\5\3\0\1\50\2\0"+
    "\1\50\2\0\3\5\1\0\7\5\1\152\1\0\6\5"+
    "\7\0\1\50\2\0\1\5\3\0\2\5\3\0\1\50"+
    "\2\0\1\50\2\0\3\5\1\0\3\5\1\153\4\5"+
    "\1\0\6\5\7\0\1\50\2\0\1\5\31\0\1\154"+
    "\43\0\2\155\34\0\2\5\3\0\1\50\2\0\1\50"+
    "\2\0\3\5\1\0\7\5\1\156\1\0\6\5\7\0"+
    "\1\50\2\0\1\5\3\0\2\5\3\0\1\50\2\0"+
    "\1\50\2\0\3\5\1\155\1\157\7\5\1\0\6\5"+
    "\7\0\1\50\2\0\1\5\3\0\2\5\3\0\1\50"+
    "\2\0\1\50\2\0\3\5\1\0\5\5\1\160\2\5"+
    "\1\0\6\5\7\0\1\50\2\0\1\5\4\0\1\136"+
    "\12\0\1\161\33\0\1\136\4\0\1\136\46\0\1\136"+
    "\3\0\1\51\1\141\2\0\1\110\6\0\3\51\1\0"+
    "\10\51\1\0\6\51\12\0\1\141\4\0\1\162\46\0"+
    "\1\162\3\0\1\110\1\163\11\0\3\110\1\0\10\110"+
    "\1\0\6\110\5\0\2\164\3\0\1\163\1\165\22\0"+
    "\1\166\33\0\2\5\3\0\1\50\2\0\1\50\2\0"+
    "\3\5\1\0\1\5\1\167\6\5\1\0\6\5\7\0"+
    "\1\50\2\0\1\5\3\0\2\5\3\0\1\50\2\0"+
    "\1\50\2\0\1\5\1\170\1\5\1\0\10\5\1\0"+
    "\6\5\7\0\1\50\2\0\1\5\3\0\2\5\3\0"+
    "\1\50\2\0\1\50\2\0\3\5\1\171\1\172\7\5"+
    "\1\0\6\5\7\0\1\50\2\0\1\5\34\0\1\173"+
    "\22\0\2\5\3\0\1\50\2\0\1\50\2\0\3\5"+
    "\1\0\10\5\1\0\1\5\1\174\4\5\7\0\1\50"+
    "\2\0\1\5\34\0\1\175\42\0\1\176\33\0\2\5"+
    "\3\0\1\50\2\0\1\50\2\0\3\5\1\0\10\5"+
    "\1\0\1\5\1\177\4\5\7\0\1\50\2\0\1\5"+
    "\3\0\2\5\3\0\1\50\2\0\1\50\2\0\3\5"+
    "\1\0\1\5\1\200\6\5\1\0\6\5\7\0\1\50"+
    "\2\0\1\5\3\0\2\5\3\0\1\50\2\0\1\50"+
    "\2\0\3\5\1\0\10\5\1\0\1\5\1\201\4\5"+
    "\7\0\1\50\2\0\1\5\4\0\1\202\41\0\2\203"+
    "\3\0\1\202\3\0\1\110\1\163\11\0\3\110\1\0"+
    "\10\110\1\0\6\110\12\0\1\163\4\0\1\162\46\0"+
    "\1\162\1\165\2\0\2\5\3\0\1\50\2\0\1\50"+
    "\2\0\3\5\1\0\4\5\1\204\3\5\1\0\6\5"+
    "\7\0\1\50\2\0\1\5\23\0\1\205\33\0\2\5"+
    "\3\0\1\50\2\0\1\50\2\0\3\5\1\0\1\5"+
    "\1\206\6\5\1\0\6\5\7\0\1\50\2\0\1\5"+
    "\21\0\2\207\51\0\1\210\36\0\2\5\3\0\1\50"+
    "\2\0\1\50\2\0\3\5\1\207\1\211\7\5\1\0"+
    "\6\5\7\0\1\50\2\0\1\5\3\0\2\5\3\0"+
    "\1\50\2\0\1\50\2\0\2\5\1\212\1\0\10\5"+
    "\1\0\6\5\7\0\1\50\2\0\1\5\3\0\2\5"+
    "\3\0\1\50\2\0\1\50\2\0\3\5\1\213\1\214"+
    "\7\5\1\0\6\5\7\0\1\50\2\0\1\5\4\0"+
    "\1\202\46\0\1\202\3\0\2\5\3\0\1\50\2\0"+
    "\1\50\2\0\3\5\1\0\1\5\1\215\6\5\1\0"+
    "\6\5\7\0\1\50\2\0\1\5\34\0\1\216\22\0"+
    "\2\5\3\0\1\50\2\0\1\50\2\0\3\5\1\0"+
    "\10\5\1\0\1\5\1\217\4\5\7\0\1\50\2\0"+
    "\1\5\23\0\1\220\33\0\2\5\3\0\1\50\2\0"+
    "\1\50\2\0\3\5\1\0\1\5\1\221\6\5\1\0"+
    "\6\5\7\0\1\50\2\0\1\5\24\0\1\222\32\0"+
    "\2\5\3\0\1\50\2\0\1\50\2\0\3\5\1\0"+
    "\2\5\1\223\5\5\1\0\6\5\7\0\1\50\2\0"+
    "\1\5\34\0\1\224\22\0\2\5\3\0\1\50\2\0"+
    "\1\50\2\0\3\5\1\0\10\5\1\0\1\5\1\225"+
    "\4\5\7\0\1\50\2\0\1\5\23\0\1\226\33\0"+
    "\2\5\3\0\1\50\2\0\1\50\2\0\3\5\1\0"+
    "\1\5\1\227\6\5\1\0\6\5\7\0\1\50\2\0"+
    "\1\5\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4796];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\1\11\3\1\2\11\14\1\2\11"+
    "\1\1\1\11\1\1\1\11\1\1\2\11\5\1\1\11"+
    "\6\1\1\11\3\1\1\0\5\1\2\0\2\1\1\0"+
    "\3\1\3\11\2\0\1\11\1\0\11\1\1\11\5\1"+
    "\2\0\2\1\1\11\3\1\2\0\2\1\1\0\1\1"+
    "\1\0\3\1\1\0\3\1\2\0\3\1\1\0\2\1"+
    "\1\0\2\11\2\1\1\0\1\1\1\11\1\1\2\0"+
    "\4\1\1\0\1\1\1\0\1\1\1\0\1\11\2\1"+
    "\1\0\2\1\1\11\1\1\1\0\1\1\1\0\1\1"+
    "\1\11\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public String lexeme;

    public int yyline() {
    	return this.yyline;
    }

    public void error(String msg, String caracteres, int linea) throws ScannerException {
        throw new ScannerException(msg, caracteres, linea+1);
    }

    private Symbol symbol(int type) {
        return new Symbol(type, yyline);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 212) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, ScannerException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case COMENTARIOS1: {
              yybegin(YYINITIAL); error("Comentario sin finalizar.", yytext(),yyline());
            }  // fall though
            case 152: break;
            case COMENTARIOS2: {
              yybegin(YYINITIAL); error("Comentario sin finalizar.", yytext(),yyline());
            }  // fall though
            case 153: break;
            default:
              {
                return symbol(sym.EOF);
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { error("El caracter es inválido", yytext(), yyline());
            } 
            // fall through
          case 44: break;
          case 2: 
            { return symbol(sym.IDENTIFICADOR);
            } 
            // fall through
          case 45: break;
          case 3: 
            { return symbol(sym.INTEGER);
            } 
            // fall through
          case 46: break;
          case 4: 
            { /*Ignore*/
            } 
            // fall through
          case 47: break;
          case 5: 
            { return symbol(sym.OpDIV);
            } 
            // fall through
          case 48: break;
          case 6: 
            { return symbol(sym.PARENTESIS_ABRE);
            } 
            // fall through
          case 49: break;
          case 7: 
            { return symbol(sym.OpMUL);
            } 
            // fall through
          case 50: break;
          case 8: 
            { yybegin(COMENTARIOS2);
            } 
            // fall through
          case 51: break;
          case 9: 
            { return symbol(sym.COMA);
            } 
            // fall through
          case 52: break;
          case 10: 
            { return symbol(sym.PUNTOYCOMA);
            } 
            // fall through
          case 53: break;
          case 11: 
            { return symbol(sym.OpMAYOR);
            } 
            // fall through
          case 54: break;
          case 12: 
            { return symbol(sym.OpIGUAL);
            } 
            // fall through
          case 55: break;
          case 13: 
            { return symbol(sym.OpMENOR);
            } 
            // fall through
          case 56: break;
          case 14: 
            { return symbol(sym.OpSUMA);
            } 
            // fall through
          case 57: break;
          case 15: 
            { return symbol(sym.OpRESTA);
            } 
            // fall through
          case 58: break;
          case 16: 
            { return symbol(sym.PARENTESIS_CIERRA);
            } 
            // fall through
          case 59: break;
          case 17: 
            { return symbol(sym.DOS_PUNTOS);
            } 
            // fall through
          case 60: break;
          case 18: 
            { yybegin(YYINITIAL);
            } 
            // fall through
          case 61: break;
          case 19: 
            { error("Identificador erróneo: no se puede utilizar caracteres especiales en los identificadores.", yytext(),yyline());
            } 
            // fall through
          case 62: break;
          case 20: 
            { error("Número erróneo: no se puede ingresar letras dentro de un número.", yytext(),yyline());
            } 
            // fall through
          case 63: break;
          case 21: 
            { error("Número erróneo: no se puede finalizar un número con punto", yytext(),yyline());
            } 
            // fall through
          case 64: break;
          case 22: 
            { error("Número erróneo: no se puede iniciar un número con punto", yytext(),yyline());
            } 
            // fall through
          case 65: break;
          case 23: 
            { yybegin(COMENTARIOS1);
            } 
            // fall through
          case 66: break;
          case 24: 
            { return symbol(sym.OpMAYOR_IGUAL);
            } 
            // fall through
          case 67: break;
          case 25: 
            { return symbol(sym.OpDIFERENTE);
            } 
            // fall through
          case 68: break;
          case 26: 
            { return symbol(sym.OpMENOR_IGUAL);
            } 
            // fall through
          case 69: break;
          case 27: 
            { return symbol(sym.STRING);
            } 
            // fall through
          case 70: break;
          case 28: 
            { return symbol(sym.FLOAT);
            } 
            // fall through
          case 71: break;
          case 29: 
            { error("Número erróneo: número no válido", yytext(),yyline());
            } 
            // fall through
          case 72: break;
          case 30: 
            { return symbol(sym.END);
            } 
            // fall through
          case 73: break;
          case 31: 
            { return symbol(sym.TYPE_INT);
            } 
            // fall through
          case 74: break;
          case 32: 
            { return symbol(sym.Op_DIV);
            } 
            // fall through
          case 75: break;
          case 33: 
            { return symbol(sym.VAR);
            } 
            // fall through
          case 76: break;
          case 34: 
            { return symbol(sym.TYPE_CHAR);
            } 
            // fall through
          case 77: break;
          case 35: 
            { return symbol(sym.TYPE_REAL);
            } 
            // fall through
          case 78: break;
          case 36: 
            { return symbol(sym.BEGIN);
            } 
            // fall through
          case 79: break;
          case 37: 
            { return symbol(sym.CONST);
            } 
            // fall through
          case 80: break;
          case 38: 
            { error("Número erróneo: no puede ser negativo el número antes del exponente", yytext(),yyline());
            } 
            // fall through
          case 81: break;
          case 39: 
            { return symbol(sym.TYPE_STRING);
            } 
            // fall through
          case 82: break;
          case 40: 
            { return symbol(sym.TYPE_BOOLEAN);
            } 
            // fall through
          case 83: break;
          case 41: 
            { return symbol(sym.TYPE_LONGINT);
            } 
            // fall through
          case 84: break;
          case 42: 
            { return symbol(sym.TYPE_SHORTINT);
            } 
            // fall through
          case 85: break;
          case 43: 
            { return symbol(sym.FUNCTION);
            } 
            // fall through
          case 86: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
