
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 27 17:41:17 CST 2018
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_DEC = 30;
  public static final int TYPE_BOOLEAN = 3;
  public static final int FUNCTION = 16;
  public static final int CONST = 10;
  public static final int PUNTOYCOMA = 27;
  public static final int PARENTESIS_CIERRA = 42;
  public static final int INTEGER = 56;
  public static final int DOS_PUNTOS = 43;
  public static final int OpRESTA = 38;
  public static final int TYPE_REAL = 7;
  public static final int OprASIG_DIV = 47;
  public static final int FOR = 15;
  public static final int TYPE_SHORTINT = 8;
  public static final int WRITE = 25;
  public static final int IDENTIFICADOR = 57;
  public static final int OpIGUAL = 36;
  public static final int CARACTER = 53;
  public static final int BOOL = 14;
  public static final int OprASIG_MUL = 46;
  public static final int BEGIN = 2;
  public static final int TYPE_INT = 5;
  public static final int IF = 17;
  public static final int OprASIG_RESTA = 45;
  public static final int OpMAYOR_IGUAL = 31;
  public static final int EOF = 0;
  public static final int Op_INC = 28;
  public static final int Op_DIV = 51;
  public static final int TYPE_LONGINT = 6;
  public static final int error = 1;
  public static final int PROGRAM = 19;
  public static final int OpSUMA = 37;
  public static final int COMA = 26;
  public static final int OpMENOR = 34;
  public static final int OpMENOR_IGUAL = 33;
  public static final int ASIGNACION = 44;
  public static final int TYPE_CHAR = 4;
  public static final int OpNOT = 50;
  public static final int OpAND = 48;
  public static final int OpMAYOR = 32;
  public static final int ELSE = 12;
  public static final int TYPE_STRING = 9;
  public static final int READ = 20;
  public static final int OpDIV = 40;
  public static final int TO = 22;
  public static final int WHILE = 24;
  public static final int FLOAT = 55;
  public static final int THEN = 21;
  public static final int OpOR = 49;
  public static final int END = 13;
  public static final int OprASIG_MAS = 29;
  public static final int STRING = 54;
  public static final int OpMUL = 39;
  public static final int OpDIFERENTE = 35;
  public static final int OpMOD = 52;
  public static final int PARENTESIS_ABRE = 41;
  public static final int VAR = 23;
  public static final int PROCEDURE = 18;
  public static final int DO = 11;
}

