
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 28 16:48:21 CST 2018
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_NOT = 21;
  public static final int OpDIV = 10;
  public static final int OpDEC = 8;
  public static final int Op_OR = 23;
  public static final int OpRESTA = 14;
  public static final int OpMENOR = 18;
  public static final int PARENTESIS_ABRE = 5;
  public static final int OpIGUAL = 15;
  public static final int PARENTESIS_CIERRA = 6;
  public static final int OpDIFERENTE = 20;
  public static final int OpMUL = 9;
  public static final int Op_DIV = 11;
  public static final int COMA = 25;
  public static final int STRING = 24;
  public static final int FLOAT = 3;
  public static final int EOF = 0;
  public static final int OpMAYOR_IGUAL = 17;
  public static final int OpMAYOR = 16;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 2;
  public static final int INTEGER = 4;
  public static final int Op_MOD = 12;
  public static final int Op_AND = 22;
  public static final int OpSUMA = 13;
  public static final int OpINC = 7;
  public static final int OpMENOR_IGUAL = 19;
}

