
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 31 19:57:34 CST 2018
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TYPE_BOOLEAN = 35;
  public static final int CONST = 2;
  public static final int PUNTOYCOMA = 3;
  public static final int PARENTESIS_CIERRA = 8;
  public static final int INTEGER = 6;
  public static final int DOS_PUNTOS = 29;
  public static final int OpRESTA = 16;
  public static final int TYPE_REAL = 36;
  public static final int TYPE_SHORTINT = 32;
  public static final int OpDEC = 10;
  public static final int IDENTIFICADOR = 4;
  public static final int OpIGUAL = 17;
  public static final int TYPE_INT = 30;
  public static final int Op_AND = 24;
  public static final int Op_NOT = 23;
  public static final int OpMAYOR_IGUAL = 19;
  public static final int EOF = 0;
  public static final int Op_DIV = 13;
  public static final int TYPE_LONGINT = 31;
  public static final int error = 1;
  public static final int OpSUMA = 15;
  public static final int COMA = 27;
  public static final int OpMENOR = 20;
  public static final int OpMENOR_IGUAL = 21;
  public static final int TYPE_CHAR = 33;
  public static final int OpMAYOR = 18;
  public static final int Op_MOD = 14;
  public static final int Op_OR = 25;
  public static final int TYPE_STRING = 34;
  public static final int OpINC = 9;
  public static final int OpDIV = 12;
  public static final int FLOAT = 5;
  public static final int STRING = 26;
  public static final int OpMUL = 11;
  public static final int OpDIFERENTE = 22;
  public static final int VAR = 28;
  public static final int PARENTESIS_ABRE = 7;
}

